language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - mkdir -p build/logs
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && vendor/bin/phpunit --testsuite "UMD Web API Integration Tests" || vendor/bin/phpunit'

after_script:
 - php vendor/bin/coveralls -v